swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile/transactions:
    get:
      security:
        - Bearer: []
      tags:
      - user Transactions monthly
      summary: user's transactions monthly API 
      description: API for fetch user's transactions monthly
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses: 
        '200':
          description: transactions retriever successful
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Bad request. Bad user's/transaction's id
        '401':
          description: Unauthorized access.
        '500':
          description: Internal Server Error
  /user/profile/transactions/details/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - fetch one transaction
      summary: user fetch one transaction API 
      description: API for only fetch one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Id's to fetch transaction 
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses: 
        '200':
          description: transaction details successfull
          schema:
            type: "object"
        '400':
          description: Bad request. Bad user's/transaction's id
        '404':
          description: transaction not found
        '500':
          description: Internal Server Error
    patch:
      tags:
        - update one transaction   
      summary: user's update one transaction API
      description: API to update details to one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Id's to fetch transaction 
          required: true
          type: integer
          format: int64
        - name: updateTransaction
          in: body
          description: details to update transaction
          required: false
          schema:
            type: "object"
      produces:
        - application/json
      responses: 
        '200':
          description: update to success
          schema:
            type: "object"
        '400':
          description: Bad request. Bad user's/transaction's id
        '404':
          description: User/transaction not found
        '500':
          description: Internal Server Error
    delete:
      tags:
        - delete details transaction   
      summary: user delete details one transaction API
      description: API to delete details to one user's transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Id's transaction to delete 
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Bad request. Bad user's/transaction's id
        '404':
          description: User/transaction not found
        '500':
          description: Internal Server Error


 
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  Transaction:
    type: object
    properties:
      transactionId:
        type: integer
        format: int64
      date:
        type: string
      description:
          type: string
      amount:
        type: number
      balance:
        type: number
      infos:
        type: object
        properties:
          transaction type:
            type: string
          catégorie:
            type: string
          note:
            type: string
          
    